vi =
  signIn: "Đăng Nhập"
  signin: "đăng nhập"
  signOut: "Đăng Xuất"
  signUp: "Tạo Tài Khoản"
  OR: "Hoặc"
  forgotPassword: "Quên mật khẩu?"
  emailAddress: "Địa chỉ Email"
  emailResetLink: "Email Reset Link"
  dontHaveAnAccount: "Chưa có tài khoản?"
  resetYourPassword: "Tạo lại mật khẩu"
  updateYourPassword: "Cập nhật mật khẩu"
  password: "Mật khẩu"
  usernameOrEmail: "Tên đăng nhập hoặc Email"
  email: "Email"
  ifYouAlreadyHaveAnAccount: "Nếu bạn đã có tài khoản rồi"
  signUpWithYourEmailAddress: "Đăng ký bằng tài khoản Email"
  username: "Tài khoản"
  optional: "Không bắt buộc"
  signupCode: "Mã đăng ký"
  clickAgree: "Click vào nút đăng ký, bạn đồng ý rằng"
  privacyPolicy: "Privacy Policy"
  terms: "Terms of Use"
  sign: "Sign"
  configure: "Tùy chỉnh"
  with: "với"
  createAccount: "Tạo tài khoản"
  and: "và"
  "Match failed":  "Không trùng khớp"
  "User not found":  "Tài khoản không tồn tại"

  error:
    minChar: "Để an toàn, mật khẩu phải có ít nhất 7 ký tự."
    pwOneLetter: "Mật khẩu phải có ít nhất một ký tự chữ."
    pwOneDigit: "Mật khẩu phải có ít nhất một ký tự số."
    usernameRequired: "Bạn phải nhập tên tài khoản."
    emailRequired: "Bạn phải nhập Email."
    signupCodeRequired: "Bạn phải nhập mã đăng ký."
    signupCodeIncorrect: "Mã đăng ký chưa chính xác."
    signInRequired: "Bạn chưa đăng nhập để thực hiện hành động này!"
    usernameIsEmail: "Tên tài khoản và địa chỉ Email không được trùng nhau."

T9n.map "vi", vi
